/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FolderSelect: typeof import('./src/pages/FolderSelect.vue')['default']
    MainWindow: typeof import('./src/components/MainWindow.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
